name: Release Drafter
on:
     push:
          branches:
               - main

permissions:
     contents: read

jobs:
     zip:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v4
               - name: Install zip
                 run: ls -al
               - name: Zip the Vale Package
                 run: zip -r spread.zip spread

     update_release_draft:
          name: Update Release Draft
          permissions:
               contents: write
               pull-requests: write
          runs-on: ubuntu-latest
          steps:
               - uses: release-drafter/release-drafter@v6
                 with:
                      commitish: main
                      publish: true
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
