name: Release Drafter

on:
     push:
          branches:
               - main
          tags:
               - 'v*'

permissions:
     contents: read

jobs:
     update_release_draft:
          name: Update Release Draft
          permissions:
               contents: write
               pull-requests: write
          runs-on: ubuntu-latest
          steps:
               - uses: release-drafter/release-drafter@v6
                 with:
                      commitish: main
                      publish: true
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     build:
          runs-on: ubuntu-latest
          steps:
               - name: Checkout code
                 uses: actions/checkout@v2

               - name: Zip the folder
                 run: |
                      zip -r spread.zip spread

               - name: Upload Release Asset
                 uses: softprops/action-gh-release@v2
                 with:
                      tag_name: ${{github.event.release.tag_name}}
                      files: spread.zip
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
