name: Release Drafter

on:
     push:
          branches:
               - main

permissions:
     contents: read

jobs:
     publish_release:
          name: Publish Release
          permissions:
               contents: write
               pull-requests: write
          runs-on: ubuntu-latest
          steps:
               - uses: release-drafter/release-drafter@v6
                 with:
                      commitish: main
                      publish: true
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
