name: Release Drafter

on:
     push:
          branches:
               - main
     pull_request_target:
          types: [opened, reopened, synchronize]

permissions:
     contents: read

jobs:
     update_release_draft:
          name: Update Release Draft
          permissions:
               contents: write
               pull-requests: write
          runs-on: ubuntu-latest
          steps:
               - uses: release-drafter/release-drafter@v6
                 with:
                      commitish: main
                      publish: true
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
