name: Release Drafter

on:
     push:
          branches:
               - main

permissions:
     contents: read

jobs:
     publish_release:
          name: Publish Release
          permissions:
               contents: write
               pull-requests: write
          runs-on: ubuntu-latest
          steps:
               - uses: release-drafter/release-drafter@v6
                 with:
                      commitish: main
                      publish: true
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               - name: Upload into Release
                 uses: softprops/action-gh-release@v2
                 with:
                      files: spread.zip
                      tag_name: ${{github.event.release.tag_name}}
