name: Release Drafter

on:
     push:
          branches:
               - main

permissions:
     contents: read

jobs:
     publish_release:
          name: Publish Release
          permissions:
               contents: write
               pull-requests: write
          runs-on: ubuntu-latest
          steps:
               - uses: release-drafter/release-drafter@v6
                 with:
                      commitish: main
                      publish: true
                 env:
                      GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
               - name: Upload into Release
                 uses: softprops/action-gh-release@v2
                 with:
                      files: spread.zip
                      tag_name: ${{ github.event.release.tag_name }}
               - name: Attach latest zip
                 uses: actions/upload-release-asset@v1
                 env:
                      GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
                 with:
                      upload_url: ${{ steps.create_release.outputs.upload_url }}
                      asset_path: ./spread.zip
                      asset_name: spread.zip
                      asset_content_type: application/zip
