name: Zip

on:
     push:
          branches:
               - main

permissions:
     contents: read

jobs:
     zip:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v4
               - name: Zip files
                 run: |
                      apt-get install zip
                      ls -al
                      zip -r spread.zip spread
